#!/bin/bash
# Print the status for iio device X
# Usage:  ./status <n>
# where <n> (default 0) is the number of an iio device

# Output should be something like
#
# Sensor name: <name>
# Channel <channel name>_en status: <channel enabled>
# Channel <channel name>_en status: <channel enabled>
# ...
# Buffer status: <buffer enabled>
# Buffer length: <buffer length>
# Current trigger: <current trigger>
#
# A sensor not in use should not have its buffer enabled 
# and should not have a current trigger


X=0
if [ $# -eq 1 ] ; then
  X=$1
fi


echo -n "Sensor name: "
cat /sys/bus/iio/devices/iio:device${X}/name

for f in /sys/bus/iio/devices/iio:device${X}/scan_elements/*_en 
do
  echo -n "Channel $f:t status: "
  cat $f
done

echo -n "Buffer status: "
cat /sys/bus/iio/devices/iio:device${X}/buffer/enable
echo -n "Buffer length: "
cat /sys/bus/iio/devices/iio:device${X}/buffer/length

echo -n "Current trigger: "
cat /sys/bus/iio/devices/iio:device${X}/trigger/current_trigger
echo ""
